/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Room, Staff, Guest, Booking, BookingRequest, ActivityLog } from "./types";

export const initialStaffList: Staff[] = [
  {
    id: "st-1",
    name: "Elena Ross",
    role: "Housekeeping Supervisor",
    avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuCkX7DGqmdA2AbcKpgXveFOdyOk6bruxbqicYvjY3K_TveIEwyu6DtL7cvNOEemA6f6PVZx9089b0qa2-O6AlK_7N3gqcL56HhWZ9WwpLoxHRoHny5xbW2L7mOnwLf5g_u4XM4v1FLV6l2_mBNnfZGeYb_oq0SD_Jj__KjeaWWKDoPCNqMAuU9GBMnbsP4vKGVktqAIPz1HfTcnV2j7Jv6XUXMGPVsBAL7rOBCNZNWotZU325A2Knjw7N94bVsrnkIr-SfA680IdQ",
  },
  {
    id: "st-2",
    name: "Marcus V.",
    role: "Front Desk Associate",
    avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuCT5ONrV_dK30gC-1ASuVbhVciGbGfa902tvNM7oLf6jlivqtBg7q3hnTz3efaMCpUAwAxWUNKJFP74lBjnTE3JqyBe-HKU1ZbV_Vt_ZJ_e1JGBTfoeuuft6IzAMW-r3fW5YzhpzDESF-U0k9Cb0f6VJWk-gtn7ftIl-9DpYP7dhUKc_y4cavnKSbda2ar-_qz88MCXN0kYb7OK9v6l7OkAi55k2oWrwEKrzcWDQPq0DxT0gCCx6gozjELlHPzGED4kfP2npcuCrQ",
  },
  {
    id: "st-3",
    name: "James L.",
    role: "Maintenance Engineer",
    avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuCgXqPwdrHgr8ETK0di2jnYD1ZIr8aqvRb_QgbAIRFlJhG8rHsWDapVOATC75W-ZK0KD-RcAAzwpSauIVmzmEcerYOCEyRFAdGmGc1ZrJar0oeBfyoG5Ox-aEyVBCosrBpsYE5qYxP7xl9K6VinfUrTl3LfKoMFjZvrlDRcTXXuXrN8ucGxHCOJPm3xISs5RqExxP5uyu6O9USDtdcHXd-tpmUYysVB63tJwN7vU9kZk5UPWh0k9k0UfoBPFImv7Xv8PNSrEfgWxg",
  },
  {
    id: "st-4",
    name: "Sarah Kim",
    role: "Reception Lead",
    avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuCHQxWgOnmPtRQ4ckr5uCYjG0Ttutdf5nQ08hocPkkt6Ll8jpFmHwbU_kpheIZcbFLsMzjNJ0PV8sm4nA5YPusApyJhpeZeiUjYEwCf4hdDkkoThtei1OSoSVIn3rIqJfwhq0CByfaIaga1JJJntRqxnJd3HfyxwAC_COBEMTASz_hTArBC8zPeGWD6aF3E8zcqkiR7gN6wjSr6JzVImIA_nTuYNblPUI5y3E0yqdXH26SXAcdLnBKJHETMRPYMUhhD201v0EVnQg",
  },
];

export const initialRooms: Room[] = [
  { id: "302", type: "Presidential Suite", floor: "Floor 03", status: "AVAILABLE", assignedStaffId: "st-1", lastAction: "Cleaned 2h ago", rate: 1250 },
  { id: "104", type: "Deluxe King", floor: "Floor 01", status: "OCCUPIED", assignedStaffId: "st-2", lastAction: "Checked-in 14:20", rate: 450 },
  { id: "215", type: "Standard Double", floor: "Floor 02", status: "DIRTY", lastAction: "Checkout 11:00", rate: 295 },
  { id: "401", type: "Executive Studio", floor: "Floor 04", status: "MAINTENANCE", assignedStaffId: "st-3", lastAction: "HVAC Repair", rate: 650 },
  { id: "112", type: "Deluxe Queen", floor: "Floor 01", status: "AVAILABLE", assignedStaffId: "st-4", lastAction: "Cleaned 5m ago", rate: 380 },
  { id: "402", type: "Deluxe Suite", floor: "Floor 04", status: "OCCUPIED", assignedStaffId: "st-1", lastAction: "Checked-in 10:15", rate: 700 },
  { id: "405", type: "Deluxe King", floor: "Floor 04", status: "AVAILABLE", assignedStaffId: "st-2", lastAction: "Cleaned 1h ago", rate: 450 },
  { id: "208", type: "Standard King", floor: "Floor 02", status: "AVAILABLE", assignedStaffId: "st-4", lastAction: "Cleaned 4h ago", rate: 295 },
  { id: "315", type: "Executive Loft", floor: "Floor 03", status: "AVAILABLE", assignedStaffId: "st-1", lastAction: "Cleaned 3h ago", rate: 550 },
  { id: "209", type: "Standard King", floor: "Floor 02", status: "DIRTY", lastAction: "Checkout 09:30", rate: 295 },
  { id: "105", type: "Garden Deluxe", floor: "Floor 01", status: "OCCUPIED", assignedStaffId: "st-2", lastAction: "Checked-in Yesterday", rate: 410 },
  { id: "812", type: "Presidential Suite", floor: "Floor 08", status: "AVAILABLE", assignedStaffId: "st-1", lastAction: "Cleaned 12h ago", rate: 1500 },
  { id: "311", type: "Deluxe King", floor: "Floor 03", status: "OCCUPIED", assignedStaffId: "st-4", lastAction: "Checked-in 16:15", rate: 450 },
  { id: "502", type: "Deluxe Suite", floor: "Floor 05", status: "DIRTY", lastAction: "Checkout 12:00", rate: 700 },
  { id: "118", type: "Deluxe Queen", floor: "Floor 01", status: "AVAILABLE", assignedStaffId: "st-4", lastAction: "Cleaned 6h ago", rate: 380 },
  { id: "622", type: "Deluxe Suite", floor: "Floor 06", status: "OCCUPIED", assignedStaffId: "st-2", lastAction: "Checked-in 18:00", rate: 720 },
  { id: "404", type: "Deluxe King", floor: "Floor 04", status: "DIRTY", lastAction: "Checkout 10:45", rate: 450 },
];

export const initialGuests: Guest[] = [
  {
    id: "g-1",
    name: "Masterson, Alistair",
    email: "a.masterson@globalinvest.com",
    phone: "+44 20 7946 0128",
    residence: "Mayfair, London, UK",
    tier: "Premier Diamond",
    memberSince: "2018",
    loyaltyPoints: 458220,
    avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuC9XWy2eyrtMWjjca6zJq0VHoxSc3wI1yxXzrZXSCDB18KX0eHWokLzKFDnoeVwhwtn6t6itvrDnJRpGNvkh_WFEvEVs8F0BoAqLiZvQcp89MFyXT0aOMaQct8XhgFk60V5YQHwSvW5wA7leF1w6J-MnXyaESEBse5Ff_EyuVEEp_HNEj4uXya6K2WmjQeU46Brg7_hjVvIjtZ-zajYFfIPPGMCVE4oUsyJmfo1fDKJEvqqLO5AotVwanh7jH5GXv5dMGm3kkMJjg",
    dietary: "Pescetarian, severe peanut allergy. Prefers still alkaline water.",
    roomPref: "High floor, away from elevators. Requires extra firm pillows.",
    opsNotes: "VIP Arrival Protocol. Personal butler: James T.",
    stayHistory: [
      { property: "BHR Premier Makati", dates: "Jun 05 - Jun 10, 2023", roomType: "Presidential Suite", spend: "$12,450.00" },
      { property: "BHR Resort Boracay", dates: "Feb 12 - Feb 19, 2023", roomType: "Beachfront Villa", spend: "$8,900.00" },
    ],
  },
  {
    id: "g-2",
    name: "Chen, Wei-Ning",
    email: "wnchen@techasia.com",
    phone: "+886 2 2718 1234",
    residence: "Xinyi District, Taipei",
    tier: "Standard",
    memberSince: "2021",
    loyaltyPoints: 12450,
    avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuCkX7DGqmdA2AbcKpgXveFOdyOk6bruxbqicYvjY3K_TveIEwyu6DtL7cvNOEemA6f6PVZx9089b0qa2-O6AlK_7N3gqcL56HhWZ9WwpLoxHRoHny5xbW2L7mOnwLf5g_u4XM4v1FLV6l2_mBNnfZGeYb_oq0SD_Jj__KjeaWWKDoPCNqMAuU9GBMnbsP4vKGVktqAIPz1HfTcnV2j7Jv6XUXMGPVsBAL7rOBCNZNWotZU325A2Knjw7N94bVsrnkIr-SfA680IdQ",
    dietary: "None. Loves espresso.",
    roomPref: "Near the gym. Low floor preferred.",
    opsNotes: "Early check-in requested if available.",
    stayHistory: [
      { property: "BHR Premier Residence", dates: "Mar 10 - Mar 14, 2024", roomType: "Garden Deluxe", spend: "$2,240.00" },
    ],
  },
  {
    id: "g-3",
    name: "Montgomery, Elena",
    email: "e.montgomery@fortune500.com",
    phone: "+1 415 555 2671",
    residence: "Pacific Heights, San Francisco, USA",
    tier: "Premier Gold",
    memberSince: "2019",
    loyaltyPoints: 184300,
    avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuB22dihDg_mZjumzmLnWG6Q9zEX3YO_M8ilVLeum2Qac9yyeoX-98mK4nD_UIJj3jHbuCktPeyXDtOtNb5rmTic-dYXEN5MpnpdIcFPwkYEOXAltbY2gcxqg-pDgW2Clzw43amF2p8yf8B5Dj5IbX71Njnt9Jan9t_0po946Ot0y8Mu_av180bpcd-I_t5nQxTePqW07R2QMDMcYlkRMw7ptj8SWJ9qLdheYOS1oUk7fYujgnI2tyG8PqKW5iLXN6RDFvGuTX67Tg",
    dietary: "Gluten free, organic teas only.",
    roomPref: "Corner suite with layout overlooking skyline.",
    opsNotes: "Director-level hospitality package. Complimentary champagne on entry.",
    stayHistory: [
      { property: "BHR Premier Orchard", dates: "Sep 22 - Sep 28, 2023", roomType: "Premier Executive Loft", spend: "$6,100.00" },
    ],
  },
  {
    id: "g-4",
    name: "Jackson, Robert",
    email: "rjackson@financelink.org",
    phone: "+1 212 555 8392",
    residence: "Tribeca, New York, USA",
    tier: "Premier Club",
    memberSince: "2020",
    loyaltyPoints: 52400,
    avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuCf4r9i_A0_GAqxQejVYW5HK9Ba0tdoTRUqWG6p_gM5gYHwT5KQ1cvijInvGFhvlzsfWanXU250413UBCpVnUInv2_XbkkLLJCSEpUEIlt3tpNxaoHHmNG-jz0WOBLD64QwVt_MQyeFyt12DXD9kzcXIK9aa_BRM7yzBS4ZT2jr2n06_RVOaMRLw_Lx0bWLm--G9Jd1MPQuBIqsBdYNSQ9iEb68pw21Cv8M5avLf9L39SroBHUoX9DTTxS_hCQe-jNu4ZB7SfMoGQ",
    dietary: "Vegan. Prefers oat milk.",
    roomPref: "Absolute quiet room, non-smoking, feathered pillows removed.",
    opsNotes: "Prefers evening turndown service at precisely 20:00.",
    stayHistory: [
      { property: "BHR Resort Boracay", dates: "Nov 02 - Nov 09, 2023", roomType: "Poolside Villa", spend: "$5,400.00" },
    ],
  },
  {
    id: "g-5",
    name: "Sato, Akiko",
    email: "sato.akiko@jcommerce.jp",
    phone: "+81 3 5555 9812",
    residence: "Shibuya, Tokyo, Japan",
    tier: "Standard",
    memberSince: "2022",
    loyaltyPoints: 8500,
    avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuCHQxWgOnmPtRQ4ckr5uCYjG0Ttutdf5nQ08hocPkkt6Ll8jpFmHwbU_kpheIZcbFLsMzjNJ0PV8sm4nA5YPusApyJhpeZeiUjYEwCf4hdDkkoThtei1OSoSVIn3rIqJfwhq0CByfaIaga1JJJntRqxnJd3HfyxwAC_COBEMTASz_hTArBC8zPeGWD6aF3E8zcqkiR7gN6wjSr6JzVImIA_nTuYNblPUI5y3E0yqdXH26SXAcdLnBKJHETMRPYMUhhD201v0EVnQg",
    dietary: "No shellfish.",
    roomPref: "Prefers humidifier and floor tatami style accessories if possible.",
    opsNotes: "Express checkout via tablet always configured.",
    stayHistory: [
      { property: "BHR Premier Makati", dates: "Dec 15 - Dec 18, 2023", roomType: "Deluxe King", spend: "$1,350.00" },
    ],
  },
];

export const initialBookings: Booking[] = [
  {
    id: "bk-1",
    guestName: "Alex Van Der Berg",
    guestTier: "Elite Platinum Member",
    roomType: "Presidential Suite",
    roomId: "302",
    startDate: "2026-06-12",
    endDate: "2026-06-16",
    nights: 4,
    status: "In House",
    rateCode: "$1,250.00 / RAC",
    pricePerNight: 1250,
  },
  {
    id: "bk-2",
    guestName: "Sofia Martinez",
    guestTier: "Direct Booking",
    roomType: "Deluxe King",
    roomId: "104",
    startDate: "2026-06-12",
    endDate: "2026-06-13",
    nights: 1,
    status: "Arriving Soon",
    rateCode: "$450.00 / BFR",
    pricePerNight: 450,
  },
  {
    id: "bk-3",
    guestName: "Jonathan Kim",
    guestTier: "Expedia GDS",
    roomType: "Standard Queen",
    roomId: "112",
    startDate: "2026-06-12",
    endDate: "2026-06-15",
    nights: 3,
    status: "Reserved",
    rateCode: "$295.00 / COR",
    pricePerNight: 295,
  },
];

export const initialRequests: BookingRequest[] = [
  {
    id: "req-1",
    roomNum: "302",
    timeAgo: "20m ago",
    guestName: "Jameson, Robert",
    startDate: "2026-06-15",
    endDate: "2026-06-19",
    nights: 4,
    status: "PENDING",
  },
  {
    id: "req-2",
    roomNum: "PH-02",
    timeAgo: "1h ago",
    guestName: "Corporate Booking",
    startDate: "2026-06-20",
    endDate: "2026-06-22",
    nights: 2,
    status: "PENDING",
  },
  {
    id: "req-3",
    roomNum: "112",
    timeAgo: "3h ago",
    guestName: "Wu, Cheng",
    startDate: "2026-06-12",
    endDate: "2026-06-14",
    nights: 2,
    status: "PAYMENT_PENDING",
  },
  {
    id: "req-4",
    roomNum: "204",
    timeAgo: "5h ago",
    guestName: "Smith, Helena",
    startDate: "2026-06-18",
    endDate: "2026-06-20",
    nights: 2,
    status: "PENDING",
  },
];

export const initialActivities: ActivityLog[] = [
  {
    id: "act-1",
    type: "checkin",
    message: "Julian Vasseur checked in to Suite 405",
    meta: "Front Desk",
    time: "10:24 AM",
  },
  {
    id: "act-2",
    type: "maintenance",
    message: "Maintenance completed in Room 312",
    meta: "Housekeeping",
    time: "09:15 AM",
  },
  {
    id: "act-3",
    type: "checkout",
    message: "Late checkout requested for Room 102",
    meta: "Guest App",
    time: "08:45 AM",
  },
  {
    id: "act-4",
    type: "booking",
    message: "Elite Member booking confirmed: Arriving today",
    meta: "System",
    time: "08:02 AM",
  },
];
